import type { VizMeta } from '../../types';

/** Kapittel 14 Mikrobielle og virale sykdommer (Bi 1). Delkapitlene er ikke bekreftet ennå, så `sections` er tom. */
const viz: VizMeta[] = [
  {
    id: 'bakterievekst',
    chapter: '14',
    sections: [],
    title: 'Bakterievekst og temperatur',
    summary:
      'Se hvordan bakterier i mat formerer seg ved todeling, med lagfase, eksponentiell fase, stasjonær fase og dødsfase. Sammenlign kjøleskap, romtemperatur og kroppstemperatur, og finn ut når maten passerer en million bakterier per gram.',
    keywords: [
      'bakterievekst',
      'vekstkurve',
      'lagfase',
      'eksponentiell fase',
      'logfase',
      'stasjonær fase',
      'dødsfase',
      'generasjonstid',
      'todeling',
      'temperatur',
      'kjøleskap',
      'matforgiftning',
      'matsikkerhet',
      'salmonella',
      'E. coli',
      'logaritmisk skala',
      'KM7',
    ],
    load: () => import('./Bakterievekst'),
  },
  {
    id: 'smittespredning',
    chapter: '14',
    sections: [],
    title: 'Smittespredning og R₀',
    summary:
      'Bygg opp basisreproduksjonstallet fra kontakter per dag, smitterisiko og dager smittsom, og se om et utbrudd vokser eller dør ut. Prøv håndvask, munnbind og isolasjon og se hvordan kurven flates ut under kapasiteten i helsevesenet.',
    keywords: [
      'smittespredning',
      'basisreproduksjonstall',
      'R0',
      'reproduksjonstall',
      'epidemi',
      'utbrudd',
      'smittevern',
      'håndvask',
      'munnbind',
      'isolasjon',
      'flate ut kurven',
      'helsevesenet',
      'SIR-modell',
      'kontakter',
      'smitterisiko',
      'KM7',
    ],
    load: () => import('./Smittespredning'),
  },
  {
    id: 'virusformering',
    chapter: '14',
    sections: [],
    title: 'Hvordan virus formerer seg',
    summary:
      'Følg en bakteriofag og et kappekledd virus gjennom feste, inntrengning, kopiering, montering og frigjøring, og sammenlign med en bakterie som deler seg. Se hvorfor antibiotika virker på bakterier, men ikke på virus.',
    keywords: [
      'virus',
      'virusformering',
      'bakteriofag',
      'lytisk syklus',
      'kappekledd virus',
      'influensa',
      'vertscelle',
      'feste',
      'inntrengning',
      'kopiering',
      'montering',
      'frigjøring',
      'knoppskyting',
      'todeling',
      'antibiotika',
      'reseptor',
      'KM7',
    ],
    load: () => import('./Virusformering'),
  },
];

export default viz;
