import type { VizMeta } from '../../types';

/** Kapittel 8 Kjernefysikk. */
const viz: VizMeta[] = [
  {
    id: 'halveringstid',
    chapter: '8',
    sections: ['8A', '8B'],
    title: 'Halveringstid og radioaktivt henfall',
    summary:
      'En prøve under en geigerteller som klikker: se 400 kjerner henfalle tilfeldig og sammenlign med halveringsformelen for karbon-14, jod-131, radon-222, kobolt-60 og uran-238.',
    keywords: [
      'radioaktivitet',
      'aktivitet',
      'becquerel',
      'desintegrasjonskonstant',
      'henfallskonstant',
      'karbondatering',
      'tilfeldig',
      'statistikk',
      'geigerteller',
      'radon',
      'alunskifer',
      'strålekilde',
      'rekkevidde',
    ],
    load: () => import('./Halveringstid'),
  },
  {
    id: 'c14',
    chapter: '8',
    sections: ['8A', '8B'],
    title: 'Karbon-14-datering: hvor gammel er prøven?',
    summary:
      'Mål hvor mye C-14 som er igjen i et vikingskip, Ötzi, trekull eller en mammut, og finn alderen. Se hvorfor metoden ikke virker for prøver som er eldre enn ca. 50 000 år.',
    keywords: [
      'karbondatering',
      'C-14',
      'aldersbestemmelse',
      'halveringstid',
      'betahenfall',
      'måleusikkerhet',
      'aktivitet',
      'arkeologi',
      'fossil',
      'KM1',
      'KM2',
    ],
    load: () => import('./C14Datering'),
  },
  {
    id: 'bindingsenergi',
    chapter: '8',
    sections: ['8A', '8B', '8C', '8D'],
    title: 'Bindingsenergi per nukleon',
    summary:
      'Se hvorfor jern og nikkel er de mest stabile kjernene, og hvorfor både fisjon av uran og fusjon av hydrogen frigjør energi: E = Δm · c².',
    keywords: ['massedefekt', 'E = mc²', 'fisjon', 'fusjon', 'kjernekraft', 'sola', 'deuterium', 'tritium', 'uran', 'jern', 'nikkel'],
    load: () => import('./Bindingsenergi'),
  },
  {
    id: 'kjernereaksjoner',
    chapter: '8',
    sections: ['8B'],
    title: 'Kjernereaksjoner: α, β og γ',
    summary: 'Velg en kjerne og en henfallstype, og se at nukleontall og ladning er bevart. Følg uranserien helt ned til stabilt bly.',
    keywords: [
      'alfastråling',
      'betastråling',
      'gammastråling',
      'bevaringslover',
      'nukleontall',
      'ladning',
      'datterkjerne',
      'uranserien',
      'positron',
      'nøytrino',
    ],
    load: () => import('./Kjernereaksjoner'),
  },
  {
    id: 'kjedereaksjon',
    chapter: '8',
    sections: ['8B', '8C'],
    title: 'Fisjon og kjedereaksjon i en reaktor',
    summary:
      'Et nøytron spalter U-235 i to mindre kjerner og 2–3 nye nøytroner. Styr hvor mange nøytroner kontrollstavene fanger, og se kjedereaksjonen dø ut, gå jevnt eller vokse.',
    keywords: [
      'fisjon',
      'kjedereaksjon',
      'formeringsfaktor',
      'kritisk',
      'kontrollstav',
      'moderator',
      'kjernekraftverk',
      'reaktor',
      'uran-235',
      'nøytron',
      'massedefekt',
      'E = mc²',
      'eksponentiell vekst',
      'KM2',
      'KM3',
      'KM7',
      'KM8',
    ],
    load: () => import('./Kjedereaksjon'),
  },
];

export default viz;
