import type { VizMeta } from '../../types';

/** Kapittel 8 Kommunikasjonssystemer i mennesket (Bi 1). Delkapitlene er ikke bekreftet ennå, så `sections` er tom. */
const viz: VizMeta[] = [
  {
    id: 'nerveimpuls',
    chapter: '8',
    sections: [],
    title: 'Nerveimpulsen',
    summary:
      'Gi en nervecelle et stimulus og se membranpotensialet, natrium- og kaliumkanalene og ionene gjennom et aksjonspotensial, refraktærperioden og hvor fort impulsen går med og uten myelin.',
    keywords: [
      'nerveimpuls',
      'aksjonspotensial',
      'hvilepotensial',
      'terskelverdi',
      'alt-eller-ingenting',
      'depolarisering',
      'repolarisering',
      'hyperpolarisering',
      'refraktærperiode',
      'natriumkanal',
      'kaliumkanal',
      'natrium-kalium-pumpe',
      'nervecelle',
      'akson',
      'myelin',
      'Schwannske celler',
      'Ranviers innsnøringer',
      'saltatorisk ledning',
      'multippel sklerose',
      'KM3',
      'KM4',
    ],
    load: () => import('./Nerveimpuls'),
  },
  {
    id: 'synapse',
    chapter: '8',
    sections: [],
    title: 'Signaloverføring i synapsen',
    summary:
      'Send nerveimpulser til en kjemisk synapse og følg Ca²⁺, vesikler, signalstoff og reseptorer. Se hva en reopptakshemmer og en reseptorblokker gjør med signalet i neste nervecelle.',
    keywords: [
      'synapse',
      'kjemisk synapse',
      'synapsespalt',
      'endeknapp',
      'signalstoff',
      'nevrotransmitter',
      'vesikkel',
      'eksocytose',
      'kalsium',
      'reseptor',
      'reopptak',
      'reopptakshemmer',
      'SSRI',
      'serotonin',
      'acetylkolin',
      'reseptorblokker',
      'summering',
      'nervecelle',
      'KM3',
      'KM4',
    ],
    load: () => import('./Synapse'),
  },
  {
    id: 'blodsukker',
    chapter: '8',
    sections: [],
    title: 'Regulering av blodsukkeret',
    summary:
      'Følg blodsukkeret, insulin og glukagon gjennom et døgn med måltider, og se hvordan negativ tilbakekobling holder det stabilt. Sammenlign med type 1- og type 2-diabetes og se hva fysisk aktivitet gjør.',
    keywords: [
      'blodsukker',
      'glukose',
      'insulin',
      'glukagon',
      'bukspyttkjertel',
      'langerhanske øyer',
      'betaceller',
      'alfaceller',
      'lever',
      'glykogen',
      'homeostase',
      'negativ tilbakekobling',
      'hormon',
      'diabetes',
      'type 1-diabetes',
      'type 2-diabetes',
      'insulinresistens',
      'fysisk aktivitet',
      'livsstil',
      'glukosebelastning',
      'KM4',
    ],
    load: () => import('./Blodsukker'),
  },
];

export default viz;
