import type { VizMeta } from '../../types';

/** Kapittel 5 Termisk energi. */
const viz: VizMeta[] = [
  {
    id: 'gassmodell',
    chapter: '5',
    sections: ['5A', '5B'],
    title: 'Gassmodell: trykk og temperatur',
    summary:
      'Varm opp gassen i en sylinder på kokeplata, eller endre volumet, og se hvordan støtene fra partiklene gir trykket på manometeret. Følg linjene ned til det absolutte nullpunktet.',
    keywords: ['partikkelmodell', 'trykk', 'kelvin', 'celsius', 'absolutt nullpunkt', 'pV = nRT', 'idealgass', 'p = F/A', 'manometer', 'stempel', 'partikkelfart'],
    load: () => import('./Gassmodell'),
  },
  {
    id: 'dekktrykk',
    chapter: '5',
    sections: ['5A', '5B'],
    title: 'Dekktrykk om vinteren',
    summary:
      'Fyll et bildekk i en varm garasje og la bilen stå ute i kulda. Se hvorfor trykket faller, hva måleren egentlig viser, og hvorfor du må regne med kelvin og absolutt trykk.',
    keywords: [
      'dekktrykk',
      'manometertrykk',
      'absolutt trykk',
      'overtrykk',
      'lufttrykk',
      'bar',
      'p/T = konstant',
      'fast volum',
      'kelvin',
      'celsius',
      'absolutt nullpunkt',
      'idealgass',
      'KM2',
      'KM10',
    ],
    load: () => import('./Dekktrykk'),
  },
  {
    id: 'blanding',
    chapter: '5',
    sections: ['5C', '5D'],
    title: 'Blanding og termisk likevekt',
    summary:
      'Varmt vann i et tynt metallbeger står i kaldt vann i et isoporkalorimeter, eller en varm metallbit senkes i vann. Følg termometrene: energien det varme avgir, mottar det kalde, helt til temperaturene er like.',
    keywords: [
      'varme',
      'indre energi',
      'termisk likevekt',
      'sluttemperatur',
      'kalorimeter',
      'isopor',
      'termometer',
      'energibevaring',
      'energioverføring',
      'spesifikk varmekapasitet',
      'Q = cmΔT',
      'blanding',
    ],
    load: () => import('./Blanding'),
  },
  {
    id: 'varmekapasitet',
    chapter: '5',
    sections: ['5D'],
    title: 'Spesifikk varmekapasitet',
    summary:
      'Sett en kasserolle med vann eller etanol og en metallkloss med samme masse på to like kokeplater. Følg termometrene og stoppeklokka: samme energi gir ulik temperaturøkning, Q = c·m·ΔT.',
    keywords: [
      'varmekapasitet',
      'Q = cmΔT',
      'effekt',
      'E = Pt',
      'oppvarming',
      'kokeplate',
      'kasserolle',
      'metallkloss',
      'termometer',
      'stoppeklokke',
      'stigningstall',
      'kokepunkt',
      'fordampingsvarme',
    ],
    load: () => import('./Varmekapasitet'),
  },
  {
    id: 'vannkoker',
    chapter: '5',
    sections: ['5C', '5D'],
    title: 'Vannkoker eller kokeplate',
    summary:
      'Kok opp like mye vann i en vannkoker og i en kasserolle på kokeplata, med samme effekt. Vannet trenger like mye varme, men varmetapet avgjør hvem som koker først og hvor mye elektrisk energi som går med.',
    keywords: [
      'vannkoker',
      'kokeplate',
      'kasserolle',
      'Q = cmΔT',
      'E = Pt',
      'effekt',
      'virkningsgrad',
      'varmetap',
      'energiregnskap',
      'energibevaring',
      'kokepunkt',
      'kWh',
      'temperatur-tid-graf',
      'KM8',
      'KM10',
    ],
    load: () => import('./Vannkoker'),
  },
  {
    id: 'forste-lov',
    chapter: '5',
    sections: ['5E'],
    title: 'Termofysikkens første lov',
    summary:
      'Luft i en stor glassylinder med stempel står på en kokeplate, en isblokk eller isopor. Press stempelet ned eller la gassen skyve det opp, og se på termometeret og energiregnskapet hvordan ΔU = W + Q bestemmer om gassen blir varmere.',
    keywords: [
      'første lov',
      'ΔU = W + Q',
      'indre energi',
      'arbeid',
      'varme',
      'fortegn',
      'energiregnskap',
      'energibevaring',
      'kompresjon',
      'utvidelse',
      'adiabatisk',
      'isoterm',
      'fast volum',
      'stempel',
      'sykkelpumpe',
      'partikkelfart',
      'KM8',
      'KM10',
    ],
    load: () => import('./ForsteLov'),
  },
  {
    id: 'varmepumpe',
    chapter: '5',
    sections: ['5E', '5F'],
    title: 'Varmepumpe eller panelovn',
    summary:
      'En luft-til-luft-varmepumpe henter varme fra kald uteluft og gir huset mye mer varme enn strømmen den bruker. Se hvorfor varmefaktoren synker når det blir kaldere, og hvor mye strøm du sparer sammenlignet med panelovner.',
    keywords: [
      'varmepumpe',
      'varmefaktor',
      'COP',
      'ε = Q/W',
      'termofysikkens andre lov',
      'første lov',
      'energibevaring',
      'kuldemedium',
      'kompressor',
      'panelovn',
      'strømforbruk',
      'kWh',
      'energiflytdiagram',
      'kelvin',
      'KM3',
      'KM8',
      'KM10',
    ],
    load: () => import('./Varmepumpe'),
  },
  {
    id: 'eks-kalorimeter',
    kind: 'eksempel',
    chapter: '5',
    sections: ['5C', '5D'],
    title: 'Hvilket metall er biten laget av?',
    summary:
      'En varm metallbit senkes ned i vann i et isolert beger. Finn den spesifikke varmekapasiteten fra likevektstemperaturen, sammenlign med tabellverdier og drøft hvordan varmetap påvirker svaret, steg for steg.',
    keywords: [
      'kalorimeter',
      'kalorimetri',
      'spesifikk varmekapasitet',
      'Q = cmΔT',
      'energibevaring',
      'termisk likevekt',
      'likevektstemperatur',
      'varmetap',
      'tabellverdi',
      'avvik i prosent',
      'isopor',
      'metall',
      'eksempeloppgave',
    ],
    load: () => import('./EksKalorimeter'),
  },
  {
    id: 'eks-gass',
    kind: 'eksempel',
    chapter: '5',
    sections: ['5A', '5B', '5E'],
    title: 'Luft i en sylinder med låst stempel',
    summary:
      'Luft i en glassylinder varmes opp i et vannbad mens en splint holder stempelet. Finn stoffmengden, trykket og kraften på splinten, og bruk ΔU = W + Q når stempelet slippes, steg for steg.',
    keywords: [
      'tilstandslikningen',
      'pV = nRT',
      'idealgass',
      'stoffmengde',
      'kelvin',
      'absolutt temperatur',
      'trykk',
      'p = F/A',
      'stempel',
      'termofysikkens første lov',
      'ΔU = W + Q',
      'indre energi',
      'arbeid',
      'varme',
      'fortegn',
      'eksempeloppgave',
    ],
    load: () => import('./EksGass'),
  },
];

export default viz;
