import type { VizMeta } from '../../types';

/** Kapittel 11 Transportsystemer i planter (Bi 1). Delkapitlene er ikke bekreftet ennå, så `sections` er tom. */
const viz: VizMeta[] = [
  {
    id: 'vann-og-mineraler',
    chapter: '11',
    sections: [],
    title: 'Vann og mineraler fra rota',
    summary:
      'Se hvordan rothårene tar opp vann ved osmose og mineraler ved aktiv transport, hvordan rottrykk gir guttasjon, og hvilke symptomer planten får når den mangler nitrogen, fosfor, kalium eller magnesium.',
    keywords: [
      'rot',
      'rothår',
      'osmose',
      'aktiv transport',
      'ioneopptak',
      'mineraler',
      'næringssalter',
      'endodermis',
      'Casparys bånd',
      'rottrykk',
      'guttasjon',
      'hydatoder',
      'nitrogen',
      'fosfor',
      'kalium',
      'magnesium',
      'mangelsymptomer',
      'klorose',
      'minimumsloven',
      'saltstress',
      'KM3',
    ],
    load: () => import('./VannOgMineraler'),
  },
  {
    id: 'transpirasjon',
    chapter: '11',
    sections: [],
    title: 'Transpirasjon og vannets vei',
    summary:
      'Endre lys, luftfuktighet, temperatur, vind og vann i jorda, og se spalteåpningene åpne og lukke seg, vannet bli dratt fra jorda til lufta og planten visne når jorda blir for tørr.',
    keywords: [
      'transpirasjon',
      'spalteåpninger',
      'lukkeceller',
      'xylem',
      'vedrør',
      'kohesjon',
      'adhesjon',
      'kohesjon–spenning',
      'vannpotensial',
      'fordampning',
      'CO₂-opptak',
      'fotosyntese',
      'turgor',
      'visning',
      'luftfuktighet',
      'KM3',
    ],
    load: () => import('./Transpirasjon'),
  },
  {
    id: 'floemtransport',
    chapter: '11',
    sections: [],
    title: 'Sukkertransport i floemet',
    summary:
      'Gjør bladene, skuddet, blomstene, røttene og knollene i en potetplante til kilder eller sluk, og se hvilken vei sukkeret strømmer i floemet etter trykkstrømmodellen, fra vår til sensommer og etter ringbarking.',
    keywords: [
      'floem',
      'silrør',
      'følgeceller',
      'sukrose',
      'kilde',
      'sluk',
      'trykkstrømmodellen',
      'Münch',
      'potet',
      'knoll',
      'ringbarking',
      'translokasjon',
      'KM3',
    ],
    load: () => import('./Floemtransport'),
  },
];

export default viz;
