import type { VizMeta } from '../../types';

/** Kapittel 6 Transport og kommunikasjon i celler (Bi 1). Delkapitlene er ikke bekreftet ennå, så `sections` er tom. */
const viz: VizMeta[] = [
  {
    id: 'diffusjon-og-osmose',
    chapter: '6',
    sections: [],
    title: 'Diffusjon og osmose',
    summary:
      'Se partikler diffundere gjennom en membran, vann strømme ved osmose, og hva som skjer med et rødt blodlegeme og en plantecelle i hypoton, isoton og hyperton løsning.',
    keywords: [
      'diffusjon',
      'osmose',
      'passiv transport',
      'fasilitert diffusjon',
      'kanalprotein',
      'akvaporin',
      'konsentrasjonsgradient',
      'halvgjennomtrengelig membran',
      'hypoton',
      'isoton',
      'hyperton',
      'hemolyse',
      'plasmolyse',
      'turgor',
      'cellemembran',
      'KM5',
    ],
    load: () => import('./DiffusjonOgOsmose'),
  },
  {
    id: 'membrantransport',
    chapter: '6',
    sections: [],
    title: 'Transport gjennom cellemembranen',
    summary:
      'Sammenlign diffusjon gjennom lipidlaget, fasilitert diffusjon gjennom kanaler og bæreproteiner (med metning), aktiv transport med natrium-kalium-pumpa og endo- og eksocytose.',
    keywords: [
      'membrantransport',
      'passiv transport',
      'diffusjon',
      'fasilitert diffusjon',
      'bæreprotein',
      'kanalprotein',
      'glukosetransportør',
      'metning',
      'aktiv transport',
      'natrium-kalium-pumpe',
      'ATP',
      'konsentrasjonsgradient',
      'endocytose',
      'eksocytose',
      'fagocytose',
      'vesikkel',
      'lipiddobbeltlag',
      'KM5',
    ],
    load: () => import('./Membrantransport'),
  },
  {
    id: 'cellesignalering',
    chapter: '6',
    sections: [],
    title: 'Hormoner og signaler til cellen',
    summary:
      'Følg et vannløselig hormon (adrenalin) via reseptor, sekundært budbringerstoff og enzymkjede, og et fettløselig hormon (kortisol) inn til DNA, og se hvordan ett hormonmolekyl forsterkes til millioner av molekyler.',
    keywords: [
      'cellesignalering',
      'kommunikasjon mellom celler',
      'hormon',
      'signalstoff',
      'reseptor',
      'målcelle',
      'vannløselig hormon',
      'fettløselig hormon',
      'steroidhormon',
      'adrenalin',
      'glukagon',
      'kortisol',
      'sekundært budbringerstoff',
      'cAMP',
      'G-protein',
      'signalkjede',
      'forsterkning',
      'genuttrykk',
      'homeostase',
      'KM4',
      'KM5',
    ],
    load: () => import('./Cellesignalering'),
  },
];

export default viz;
