import type { VizMeta } from '../../types';

/** Kapittel 9 Transportsystemer i mennesket (Bi 1). Delkapitlene er ikke bekreftet ennå, så `sections` er tom. */
const viz: VizMeta[] = [
  {
    id: 'hjertet-og-kretslopet',
    chapter: '9',
    sections: [],
    title: 'Hjertet og det doble kretsløpet',
    summary:
      'Se hjertet slå med forkamre, hjertekamre og klaffer gjennom systole og diastole, og følg oksygenrikt og oksygenfattig blod gjennom lungekretsløpet og kroppskretsløpet. Endre puls og slagvolum og se minuttvolumet.',
    keywords: [
      'hjertet',
      'blodomløp',
      'dobbelt kretsløp',
      'lungekretsløpet',
      'kroppskretsløpet',
      'forkammer',
      'hjertekammer',
      'seilklaff',
      'lommeklaff',
      'systole',
      'diastole',
      'puls',
      'slagvolum',
      'minuttvolum',
      'aorta',
      'lungearterie',
      'lungevene',
      'hulvene',
      'arterie',
      'vene',
      'kapillær',
      'oksygenrikt blod',
      'KM3',
    ],
    load: () => import('./HjertetOgKretslopet'),
  },
  {
    id: 'gassutveksling',
    chapter: '9',
    sections: [],
    title: 'Gassutveksling og hemoglobin',
    summary:
      'Se O₂ og CO₂ diffundere mellom alveolene, blodet og vevet etter forskjeller i partialtrykk, og bruk metningskurven til hemoglobin til å se hvor mye oksygen en arbeidende muskel får (Bohr-effekten), også i høyden.',
    keywords: [
      'gassutveksling',
      'alveole',
      'lungene',
      'kapillær',
      'diffusjon',
      'partialtrykk',
      'oksygen',
      'karbondioksid',
      'hemoglobin',
      'røde blodlegemer',
      'metningskurve',
      'oksygenmetning',
      'Bohr-effekten',
      'pH',
      'celleånding',
      'høyde',
      'KM3',
    ],
    load: () => import('./Gassutveksling'),
  },
  {
    id: 'fordoyelse-og-enzymer',
    chapter: '9',
    sections: [],
    title: 'Fordøyelse og enzymer',
    summary:
      'Følg stivelse, proteiner og fett gjennom fordøyelseskanalen og se hvor de brytes ned og tas opp. Utforsk hvordan pH og temperatur påvirker enzymene amylase, pepsin, trypsin og lipase.',
    keywords: [
      'fordøyelse',
      'fordøyelseskanalen',
      'enzym',
      'amylase',
      'pepsin',
      'trypsin',
      'lipase',
      'stivelse',
      'glukose',
      'protein',
      'aminosyrer',
      'fett',
      'fettsyrer',
      'glyserol',
      'galle',
      'magesekk',
      'tynntarm',
      'tarmtott',
      'bukspyttkjertel',
      'pH-optimum',
      'temperaturoptimum',
      'denaturering',
      'aktivt sete',
      'KM3',
    ],
    load: () => import('./FordoyelseOgEnzymer'),
  },
];

export default viz;
