import type { VizMeta } from '../../types';

/**
 * Kapittel 2 Krefter og Newtons lover. Rekkefølgen er slik at det en visualisering bygger på, kommer før:
 * skråplanet bruker friksjonstallene (2C) og Newtons 2. lov (2E), og luftmotstand bruker 2. lov og Eulers metode (2F).
 */
const viz: VizMeta[] = [
  {
    id: 'friksjon',
    chapter: '2',
    sections: ['2C'],
    title: 'Statisk friksjon og glidefriksjon',
    summary: 'Dytt en tung kasse over tregulv, betong eller is, og se hvordan friksjonen følger dyttet helt til kassen begynner å gli.',
    keywords: ['friksjonstall', 'statisk friksjon', 'glidefriksjon', 'normalkraft', 'akselerasjon', 'kasse', 'tregulv', 'betong', 'is'],
    load: () => import('./Friksjon'),
  },
  {
    id: 'fore-og-bremsing',
    chapter: '2',
    sections: ['2C', '2E'],
    title: 'Friksjon og føre: bremselengde for en bil',
    summary:
      'Brems fullt på tørr asfalt, våt asfalt, snø eller is, med sommer- eller vinterdekk og med ABS eller låste hjul, og se om du rekker å stoppe før bilen i køen. Friksjonen R = μmg gir a = μg og bremselengden v₀²/(2μg).',
    keywords: [
      'friksjonstall',
      'statisk friksjon',
      'glidefriksjon',
      'bremselengde',
      'bremsekraft',
      'ABS',
      'låste hjul',
      'vinterdekk',
      'føre',
      'is',
      'snø',
      'andre lov',
      'tidløs likning',
      'kø',
      'sammenstøt',
      'trafikk',
      'KM2',
      'KM4',
      'KM5',
    ],
    load: () => import('./ForeOgBremsing'),
  },
  {
    id: 'kraftpar',
    chapter: '2',
    sections: ['2D'],
    title: 'Kraftpar: bok, bord og jord',
    summary:
      'En lærebok ligger på skrivebordet. Følg kraftparene etter Newtons 3. lov helt ned til jordas sentrum, dytt på boka med hånda, og se med en sjekkliste hvorfor G og N ikke er et kraftpar.',
    keywords: [
      'tredje lov',
      'Newtons 3. lov',
      'kraftpar',
      'motkraft',
      'kjennetegn på kraftpar',
      'frilegemediagram',
      'gravitasjon',
      'normalkraft',
      'kontaktkraft',
      'dytt',
      'kraftsum',
      'første lov',
      'bok på bord',
      'skrivebord',
      'jordas sentrum',
    ],
    load: () => import('./KraftparTredjeLov'),
  },
  {
    id: 'tautrekking',
    chapter: '2',
    sections: ['2B', '2C', '2D', '2E'],
    title: 'Tautrekking: hvem drar hardest?',
    summary:
      'To lag drar i et tau på gress, i sokker på gulv eller på is. Tauet drar like hardt i begge lagene, så det er friksjonen fra bakken som avgjør hvem som vinner, ikke hvem som er sterkest.',
    keywords: [
      'tautrekking',
      'dragkamp',
      'tredje lov',
      'Newtons 3. lov',
      'kraftpar',
      'snordrag',
      'friksjon',
      'statisk friksjon',
      'glidefriksjon',
      'friksjonstall',
      'indre krefter',
      'ytre krefter',
      'system',
      'første lov',
      'andre lov',
      'kraftsum',
      'gress',
      'sokker',
      'is',
      'KM5',
    ],
    load: () => import('./Tautrekking'),
  },
  {
    id: 'koblede-klosser',
    chapter: '2',
    sections: ['2E'],
    title: 'Bil med tilhenger: velg system',
    summary:
      'En bil trekker en tilhenger med ved. Velg om systemet er hele vogntoget, bare hengeren eller bare bilen, og se at kraften i hengerfestet faller ut av kraftsummen når begge er med.',
    keywords: [
      'andre lov',
      'Newtons 2. lov',
      'koblede klosser',
      'koblede legemer',
      'system',
      'systemgrense',
      'snordrag',
      'indre krefter',
      'ytre krefter',
      'kraftsum',
      'tilhenger',
      'hengerfeste',
      'vogntog',
      'drivkraft',
      'tredje lov',
      'kraftpar',
    ],
    load: () => import('./KobledeKlosser'),
  },
  {
    id: 'skraplan',
    chapter: '2',
    sections: ['2A', '2C', '2E'],
    title: 'Kloss på skråplan',
    summary:
      'Løft en planke på labbenken med en kloss av tre, aluminium, gummi eller is. Se hvordan tyngden deles i G∥ og G⊥, og ved hvilken vinkel klossen begynner å gli.',
    keywords: [
      'skråplan',
      'vippbart skråplan',
      'planke',
      'gradskive',
      'dekomponering',
      'komponenter',
      'grensevinkel',
      'normalkraft',
      'friksjonstall',
      'statisk friksjon',
      'glidefriksjon',
      'akselerasjon',
      'andre lov',
      'kraftsum',
      'måle friksjonstall',
      'tre',
      'aluminium',
      'gummi',
      'is',
      'KM1',
      'KM5',
    ],
    load: () => import('./Skraplan'),
  },
  {
    id: 'heis',
    chapter: '2',
    sections: ['2B', '2E'],
    title: 'Vekt i heis',
    summary:
      'Stå på en badevekt i heisen i en boligblokk og kjør opp, ned eller se hva som skjer når vaierne ryker. Vekta viser N/g, så det er akselerasjonen, ikke farten, som bestemmer hva den viser.',
    keywords: [
      'andre lov',
      'Newtons 2. lov',
      'første lov',
      'normalkraft',
      'tilsynelatende vekt',
      'badevekt',
      'heis',
      'heissjakt',
      'boligblokk',
      'kraftsum',
      'akselerasjon',
      'konstant fart',
      'vektløs',
      'fritt fall',
      'nødbrems',
      'KM5',
    ],
    load: () => import('./Heis'),
  },
  {
    id: 'luftmotstand',
    chapter: '2',
    sections: ['2C', '2F'],
    title: 'Fall med luftmotstand',
    summary: 'Følg en fallskjermhopper fra utspranget: luftmotstanden vokser med farten til den blir like stor som tyngden, og farten blir konstant.',
    keywords: ['terminalfart', 'luftmotstand', 'kv²', 'fallskjermhopper', 'Eulers metode', 'numerisk', 'andre lov'],
    load: () => import('./Luftmotstand'),
  },
  {
    id: 'strikkhopp',
    chapter: '2',
    sections: ['2E', '2F'],
    title: 'Strikkhopp fra en bro',
    summary:
      'Velg masse, strikklengde og stivhet, og følg kreftene, høyden, farten og akselerasjonen fra fritt fall til det laveste punktet. Når er farten størst, og hvor stor blir akselerasjonen?',
    keywords: ['strikkraft', 'fjærkraft', 'Hookes lov', 'kraftsum', 'andre lov', 'fritt fall', 'laveste punkt', 'største akselerasjon', 'grafer', 'KM5', 'KM6'],
    load: () => import('./Strikkhopp'),
  },
  {
    id: 'eks-skraplan',
    kind: 'eksempel',
    chapter: '2',
    sections: ['2C', '2E'],
    title: 'Kasse som sklir ned en rampe',
    summary: 'Krefter, dekomponering av tyngden, Newtons 2. lov, fart nederst og grensevinkelen, steg for steg.',
    keywords: ['skråplan', 'rampe', 'friksjonstall', 'dekomponering', 'andre lov', 'grensevinkel', 'tidløs likning'],
    load: () => import('./EksSkraplan'),
  },
  {
    id: 'eks-trinse',
    kind: 'eksempel',
    chapter: '2',
    sections: ['2B', '2C', '2E'],
    title: 'Vogn og lodd over en trinse',
    summary:
      'Krefter på vogna og loddet, akselerasjonen til systemet, snordraget og hvorfor det er mindre enn tyngden til loddet, farten og hva friksjon endrer, steg for steg.',
    keywords: [
      'trinse',
      'snordrag',
      'lodd',
      'dynamikkvogn',
      'koblede legemer',
      'system',
      'indre krefter',
      'andre lov',
      'Newtons 2. lov',
      'første lov',
      'glidefriksjon',
      'friksjonstall',
      'tidløs likning',
    ],
    load: () => import('./EksTrinse'),
  },
];

export default viz;
