import type { VizMeta } from '../../types';

/** Kapittel 3 Mekanisk energi. */
const viz: VizMeta[] = [
  {
    id: 'arbeid',
    chapter: '3',
    sections: ['3B'],
    title: 'Arbeid: dra en kjelke på skrå',
    summary:
      'Dra lillesøster på kjelken med tauet på skrå. Se når arbeidet blir positivt, null eller negativt, hvordan friksjonen gjør negativt arbeid, og at arbeidet er arealet under kraft–strekning-grafen.',
    keywords: [
      'arbeid',
      'kjelke',
      'tau',
      'kraftkomponent',
      'dekomponering',
      'cos',
      'friksjonsarbeid',
      'totalt arbeid',
      'kinetisk energi',
      'areal under graf',
      'joule',
      'hverdag',
    ],
    load: () => import('./Arbeid'),
  },
  {
    id: 'trappelop',
    chapter: '3',
    sections: ['3A', '3B', '3C'],
    title: 'Arbeid og effekt i trappa',
    summary:
      'Løp opp en steintrapp i lia mens venninnen tar tida. Se kreftene i lupen, regn ut arbeidet W = mgh og effekten P = W/t, og sammenlign med lyspærer, mikrobølgeovn og vannkoker.',
    keywords: [
      'effekt',
      'watt',
      'arbeid',
      'joule',
      'mgh',
      'tyngde',
      'potensiell energi',
      'energi',
      'virkningsgrad',
      'trapp',
      'steintrapp',
      'stoppeklokke',
      'trening',
      'hverdag',
      'KM5',
      'KM8',
    ],
    load: () => import('./Trappelop'),
  },
  {
    id: 'sykkel-bakke',
    chapter: '3',
    sections: ['3B', '3C', '3F'],
    title: 'Sykle opp bakken: effekt, kraft og fart',
    summary:
      'Velg masse, effekt og stigning, og se hvor fort du sykler opp skolebakken, Trollstigen eller Alpe d’Huez. Konstant fart gir F = G∥ + R, og P = F · v gir farten, tida og arbeidet.',
    keywords: [
      'sykkel',
      'sykle',
      'motbakke',
      'stigning',
      'Trollstigen',
      'effekt',
      'watt',
      'P = F · v',
      'kraft',
      'fart',
      'arbeid',
      'potensiell energi',
      'rullefriksjon',
      'luftmotstand',
      'dekomponering',
      'skråplan',
      'termisk energi',
      'watt per kilo',
      'gir',
      'hverdag',
      'KM5',
      'KM8',
    ],
    load: () => import('./SykkelBakke'),
  },
  {
    id: 'energibevaring',
    chapter: '3',
    sections: ['3C', '3D', '3E', '3F'],
    title: 'Bevaring av mekanisk energi',
    summary:
      'Følg en skater i en halfpipe eller et akebrett over kulen i akebakken, og se potensiell og kinetisk energi bytte plass i energistolpene. Med friksjon blir mekanisk energi til termisk energi (varme), og du kommer ikke like høyt igjen.',
    keywords: [
      'potensiell energi',
      'kinetisk energi',
      'mekanisk energi',
      'energibevaring',
      'energistolper',
      'friksjonsarbeid',
      'termisk energi',
      'varme',
      'referansenivå',
      'nullnivå',
      'normalkraft',
      'skateboard',
      'halfpipe',
      'akebrett',
      'akebakke',
      'vendepunkt',
      'hverdag',
      'KM5',
      'KM7',
      'KM8',
    ],
    load: () => import('./Energibevaring'),
  },
  {
    id: 'berg-og-dal',
    chapter: '3',
    sections: ['3C', '3D', '3E', '3F'],
    title: 'Berg-og-dal-bane: kommer vogna over toppen?',
    summary: 'Velg starthøyden og se farten i hvert punkt fra energibevaring, energistolpene og om vogna kommer over neste topp, med og uten friksjon. Hvorfor må første topp være høyest?',
    keywords: [
      'berg-og-dal-bane',
      'fornøyelsespark',
      'energibevaring',
      'mekanisk energi',
      'potensiell energi',
      'kinetisk energi',
      'fart',
      'friksjonsarbeid',
      'termisk energi',
      'energistolper',
      'nullnivå',
      'KM5',
      'KM7',
      'KM8',
    ],
    load: () => import('./BergOgDal'),
  },
  {
    id: 'vannkraft',
    chapter: '3',
    sections: ['3A', '3C', '3F'],
    title: 'Vannkraftverk: fra magasin til stikkontakt',
    summary:
      'Vann fra et magasin faller gjennom rørgata til turbinen. Endre fallhøyde, vannføring og virkningsgrad, se effekten P = η·ρ·g·Q·h og hvor mange husstander kraftverket forsyner.',
    keywords: [
      'vannkraft',
      'kraftverk',
      'magasin',
      'demning',
      'rørgate',
      'turbin',
      'generator',
      'fallhøyde',
      'vannføring',
      'effekt',
      'virkningsgrad',
      'potensiell energi',
      'energiomforming',
      'energikvalitet',
      'husstander',
      'fornybar energi',
      'hverdag',
      'KM3',
      'KM5',
      'KM8',
    ],
    load: () => import('./Vannkraft'),
  },
];

export default viz;
