import type { VizMeta } from '../../types';

/** Kapittel 1 Rettlinjet bevegelse. */
const viz: VizMeta[] = [
  {
    id: 'fartskontroll',
    chapter: '1',
    sections: ['1B', '1C'],
    title: 'Streknings-ATK: snittfart og momentanfart',
    summary:
      'Styr farten til en bil gjennom en strekning med fartskamera i hver ende og se om sjåføren får bot. Snittfarten er stigningstallet til sekanten i s-t-grafen, momentanfarten stigningstallet til tangenten.',
    keywords: [
      'streknings-ATK',
      'fartskontroll',
      'snittfart',
      'gjennomsnittsfart',
      'momentanfart',
      'speedometer',
      'sekant',
      'tangent',
      'stigningstall',
      's-t-graf',
      'v-t-graf',
      'trafikk',
      'KM4',
    ],
    load: () => import('./Fartskontroll'),
  },
  {
    id: 'bevegelsesgrafer',
    chapter: '1',
    sections: ['1C'],
    title: 'Bevegelsesgrafer: s-t, v-t og a-t',
    summary:
      'En bil kjører langs en vei med målebånd. Styr startposisjon, startfart og akselerasjon og se bilen og de tre grafene henge sammen: stigningstall er fart, og areal under v-t-grafen er forflytning.',
    keywords: [
      'posisjon',
      'fart',
      'akselerasjon',
      'stigningstall',
      'tangent',
      'areal',
      'forflytning',
      'strekning',
      'grafisk framstilling',
      'bil',
      'målebånd',
      'rygge',
      'vendepunkt',
    ],
    load: () => import('./Bevegelsesgrafer'),
  },
  {
    id: 'bremselengde',
    chapter: '1',
    sections: ['1D'],
    title: 'Reaksjonslengde og bremselengde',
    summary:
      'En elg står i veien. Endre fart, reaksjonstid og føre og se om bilen rekker å stoppe, eller hvor fort den treffer. Dobbel fart gir dobbelt så lang reaksjonslengde, men fire ganger så lang bremselengde.',
    keywords: [
      'stopplengde',
      'reaksjonslengde',
      'reaksjonstid',
      'bremselengde',
      'bremseakselerasjon',
      'konstant akselerasjon',
      'v² − v₀² = 2as',
      'elg',
      'føre',
      'glatt føre',
      'våt asfalt',
      'snø',
      'is',
      'mobilbruk',
      'trafikk',
      'v-t-graf',
      'areal under grafen',
    ],
    load: () => import('./Bremselengde'),
  },
  {
    id: 'gult-lys',
    chapter: '1',
    sections: ['1B', '1D'],
    title: 'Gult lys: stoppe eller kjøre videre?',
    summary:
      'Lyset blir gult mens du nærmer deg et lyskryss. Med fart, reaksjonstid, bremsing og gultid ser du om bilen kan stoppe før stopplinja eller rekke over krysset før rødt, og hvor dilemmasonen er der ingen av delene går.',
    keywords: [
      'gult lys',
      'lyskryss',
      'trafikklys',
      'dilemmasone',
      'gultid',
      'stopplinje',
      'stopplengde',
      'reaksjonslengde',
      'reaksjonstid',
      'bremselengde',
      'bremseakselerasjon',
      'konstant fart',
      'konstant akselerasjon',
      's = vt',
      'v² − v₀² = 2as',
      'trafikk',
      'KM2',
      'KM4',
    ],
    load: () => import('./GultLys'),
  },
  {
    id: 'forbikjoring',
    chapter: '1',
    sections: ['1B', '1C', '1D'],
    title: 'Forbikjøring på landeveien',
    summary:
      'En bil akselererer forbi en lastebil mens en bil kommer imot. Velg fart, akselerasjon og avstand og se hvor lang tid og strekning forbikjøringen tar, om bilen rekker det, og s-t- og v-t-grafene til alle tre kjøretøyene.',
    keywords: [
      'forbikjøring',
      'lastebil',
      'vogntog',
      'møtende bil',
      'relativ bevegelse',
      'relativ fart',
      'konstant akselerasjon',
      's = v₀t + ½at²',
      'v = v₀ + at',
      'fartsgrense',
      's-t-graf',
      'v-t-graf',
      'skjæringspunkt',
      'areal under grafen',
      'trafikk',
      'KM2',
      'KM4',
    ],
    load: () => import('./Forbikjoring'),
  },
  {
    id: 'loddrett-kast',
    chapter: '1',
    sections: ['1D'],
    title: 'Loddrett kast',
    summary:
      'Mia kaster en tennisball rett opp i skolegården eller fra en balkong, og Jonas tar imot. Følg høyden og fartspila i scenen og grafene: i toppunktet er farten null, men akselerasjonen er fortsatt −g.',
    keywords: [
      'fritt fall',
      'kast rett opp',
      'toppunkt',
      'tyngdeakselerasjon',
      'konstant akselerasjon',
      'fortegn',
      'positiv retning',
      'nullnivå',
      'tidløs formel',
      'v² − v₀² = 2as',
      'tangent',
      'stoppeklokke',
      'balkong',
      'skolegård',
      's-t-graf',
      'v-t-graf',
    ],
    load: () => import('./LoddrettKast'),
  },
  {
    id: 'simulering',
    chapter: '1',
    sections: ['1E'],
    title: 'Simulering av fall med luftmotstand',
    summary:
      'En fallskjermhopper hopper ut av flyet 4 000 m over bakken. Velg kroppsstilling og gå gjennom Eulers metode steg for steg: luftmotstanden og akselerasjonen regnes ut fra farten i starten av hvert steg, og farten nærmer seg terminalfarten. Se hvordan feilen vokser når tidssteget blir større.',
    keywords: [
      'eulers metode',
      'tidssteg',
      'luftmotstand',
      'L = kv²',
      'terminalfart',
      'fallskjermhopper',
      'hoppfly',
      'fritt fall',
      'kroppsstilling',
      'kraftsum',
      'stigningstall',
      'v-t-graf',
      'høydemåler',
      'numerisk',
      'programmering',
      'python',
    ],
    load: () => import('./Simulering'),
  },
  {
    id: 'eks-vt-graf',
    kind: 'eksempel',
    chapter: '1',
    sections: ['1B', '1C', '1D'],
    title: 'Bil i bytrafikk: les av en v-t-graf',
    summary:
      'En bil kjører fra ett lyskryss til det neste. Les av v-t-grafen, finn akselerasjonen som stigningstall og strekningen som areal, regn ut gjennomsnittsfarten og skisser s-t-grafen, steg for steg.',
    keywords: [
      'eksempeloppgave',
      'v-t-graf',
      's-t-graf',
      'lese av graf',
      'stigningstall',
      'stigningstrekant',
      'akselerasjon',
      'nedbremsing',
      'areal under grafen',
      'strekning',
      'trapes',
      'gjennomsnittsfart',
      'snittfart',
      'konstant fart',
      'konstant akselerasjon',
      'lyskryss',
      'fartsgrense',
      'bytrafikk',
      'KM4',
    ],
    load: () => import('./EksVtGraf'),
  },
  {
    id: 'eks-kast-balkong',
    kind: 'eksempel',
    chapter: '1',
    sections: ['1D', '1E'],
    title: 'Golfball kastet rett opp fra en balkong',
    summary:
      'En golfball kastes rett opp fra en balkong og lander på plenen. Finn toppunktet, løs andregradslikningen for tiden og velg riktig løsning, finn farten ved plenen og drøft om det er rimelig å se bort fra luftmotstanden, steg for steg.',
    keywords: [
      'eksempeloppgave',
      'loddrett kast',
      'kast rett opp',
      'balkong',
      'golfball',
      'toppunkt',
      'tyngdeakselerasjon',
      'konstant akselerasjon',
      'positiv retning',
      'fortegn',
      'tidløs formel',
      'v² − v₀² = 2as',
      's = v₀t + ½at²',
      'andregradslikning',
      'abc-formelen',
      'negativ løsning',
      'luftmotstand',
      'L = kv²',
      'drøfting',
      'eulers metode',
      'simulering',
      's-t-graf',
      'v-t-graf',
    ],
    load: () => import('./EksKastBalkong'),
  },
];

export default viz;
