import type { VizMeta } from '../../types';

/** Kapittel 7 Atomfysikk. */
const viz: VizMeta[] = [
  {
    id: 'atomets-oppbygning',
    chapter: '7',
    sections: ['7A', '8A'],
    title: 'Bygg et atom: protoner, nøytroner og elektroner',
    summary:
      'Velg protoner, nøytroner og elektroner, eller klikk i periodesystemet, og se grunnstoffet, isotopen og ionet du får, kjernen forstørret og hvor liten den er: som en ert midt på en fotballbane.',
    keywords: [
      'protontall',
      'nukleontall',
      'nøytrontall',
      'isotop',
      'ion',
      'elektronskall',
      'kjerne',
      'grunnstoff',
      'atomnummer',
      'periodesystemet',
      'periode',
      'gruppe',
      'nuklidesymbol',
      'målestokk',
      'tomrom',
    ],
    load: () => import('./AtometsOppbygning'),
  },
  {
    id: 'rutherford',
    chapter: '7',
    sections: ['7A'],
    title: 'Rutherfords forsøk: α-partikler mot en tynn gullfolie',
    summary:
      'Skyt α-partikler mot gullfolie og tell hvor de havner. Sammenlign med det Thomsons rosinbolle forutsier, og se hvorfor de få som kastes tilbake, viser at atomet har en liten, tung og positiv kjerne.',
    keywords: [
      'Rutherford',
      'Thomson',
      'rosinbollemodellen',
      'spredningsforsøk',
      'alfapartikkel',
      'α-partikkel',
      'gullfolie',
      'avbøyning',
      'atomkjerne',
      'atommodell',
      'americium',
      'røykvarsler',
      'KM1',
      'KM2',
      'KM13',
    ],
    load: () => import('./Rutherford'),
  },
  {
    id: 'bohr-hydrogen',
    chapter: '7',
    sections: ['7B', '7C'],
    title: 'Bohrs atommodell: energinivåer i hydrogen',
    summary:
      'Et spektralrør som lyser rosa og sollys gjennom solatmosfæren: velg en overgang mellom to energinivåer, se elektronet hoppe mellom banene i ett hydrogenatom og fotonet som sendes ut eller tas opp, med energi, frekvens og bølgelengde.',
    keywords: [
      'energinivå',
      'foton',
      'Balmer',
      'Lyman',
      'Paschen',
      'emisjon',
      'absorpsjon',
      'grunntilstand',
      'ionisering',
      'E = hf',
      'spektralrør',
      'elektronbane',
      'Bohr-radius',
      'solatmosfære',
      'mørke linjer',
    ],
    load: () => import('./BohrHydrogen'),
  },
  {
    id: 'spektre',
    chapter: '7',
    sections: ['7C'],
    title: 'Spektre: kontinuerlig, emisjon og absorpsjon',
    summary:
      'Send lys fra en glødelampe, et spektralrør eller gjennom kald gass inn i et prisme og se spekteret på skjermen. Sammenlign hydrogen, helium, natrium og kvikksølv med sollys: linjene er fingeravtrykk for grunnstoffene.',
    keywords: [
      'spektrallinjer',
      'linjespekter',
      'emisjonsspekter',
      'absorpsjonsspekter',
      'kontinuerlig spekter',
      'Fraunhofer',
      'sollys',
      'fingeravtrykk',
      'fotonenergi',
      'prisme',
      'spektralrør',
      'gassutladningsrør',
      'glødelampe',
      'spalte',
      'natriumlampe',
      'lysstoffrør',
    ],
    load: () => import('./Spektre'),
  },
  {
    id: 'stjernespekter',
    chapter: '7',
    sections: ['7B', '7C'],
    title: 'Hva består stjernene av? Spektroskopi med teleskop',
    summary:
      'Rett et lite teleskop med gitter mot Vega, Capella, Arcturus eller Bellatrix, og slå på grunnstoffer til linjene fra laboratoriet treffer de mørke linjene i stjernelyset. Se hvorfor linjene er mørke: atomer i den kjøligere atmosfæren tar opp fotoner med bestemt energi.',
    keywords: [
      'stjernespekter',
      'spektroskopi',
      'absorpsjonslinjer',
      'mørke linjer',
      'stjerneatmosfære',
      'grunnstoff',
      'hydrogen',
      'helium',
      'natrium',
      'kalsium',
      'jern',
      'Balmer',
      'teleskop',
      'gitter',
      'Wiens forskyvningslov',
      'KM1',
      'KM2',
      'KM11',
      'KM13',
    ],
    load: () => import('./Stjernespekter'),
  },
  {
    id: 'nordlys',
    chapter: '7',
    sections: ['7B', '7C'],
    title: 'Nordlys: grønt, rødt og blåfiolett lys fra lufta',
    summary:
      'Elektroner fra solvinden får oksygen og nitrogen til å sende ut fotoner med bestemte farger. Se hvilken høyde hver farge kommer fra, overgangen mellom energinivåene og fotonenergien.',
    keywords: [
      'nordlys',
      'oksygen',
      'nitrogen',
      'eksitasjon',
      'energinivå',
      'foton',
      'fotonenergi',
      'E = hf',
      'linjespekter',
      'solvind',
      'KM2',
      'KM13',
    ],
    load: () => import('./Nordlys'),
  },
  {
    id: 'eks-hydrogen',
    kind: 'eksempel',
    chapter: '7',
    sections: ['7B', '7C'],
    title: 'Hydrogen i en stjernetåke: sprang, fotoner og ionisering',
    summary:
      'Energinivåene i hydrogen, fotonet fra et sprang, bølgelengden og fargen, og ioniseringsenergien fra grunntilstanden og fra et eksitert nivå, steg for steg.',
    keywords: [
      'eksempeloppgave',
      'Bohrs atommodell',
      'energinivå',
      'foton',
      'fotonenergi',
      'E = hf',
      'bølgelengde',
      'synlig lys',
      'ultrafiolett',
      'infrarødt',
      'ioniseringsenergi',
      'ionisering',
      'elektronvolt',
      'stjernetåke',
      'Orion-tåken',
      'Balmer',
      'KM2',
      'KM13',
    ],
    load: () => import('./EksHydrogen'),
  },
  {
    id: 'eks-foton',
    kind: 'eksempel',
    chapter: '7',
    sections: ['7C'],
    title: 'Laserpekere og UV-stråling: energien til ett foton',
    summary:
      'Fotonenergien fra bølgelengden, antall fotoner per sekund fra effekten, en rød og en grønn laserpeker med samme effekt, og hvorfor UV-B kan skade DNA i huden når synlig lys ikke kan, steg for steg.',
    keywords: [
      'eksempeloppgave',
      'foton',
      'fotonenergi',
      'E = hf',
      'E = hc/λ',
      'bølgelengde',
      'elektronvolt',
      'effekt',
      'fotoner per sekund',
      'laser',
      'laserpeker',
      'ultrafiolett',
      'UV-B',
      'solbrent',
      'DNA',
      'synlig lys',
      'KM2',
      'KM13',
    ],
    load: () => import('./EksFoton'),
  },
];

export default viz;
