import type { VizMeta } from '../../types';

/** Kapittel 7 Atomfysikk. */
const viz: VizMeta[] = [
  {
    id: 'atomets-oppbygning',
    chapter: '7',
    sections: ['7A', '8A'],
    title: 'Bygg et atom: protoner, nøytroner og elektroner',
    summary:
      'Velg protoner, nøytroner og elektroner, eller klikk i periodesystemet, og se grunnstoffet, isotopen og ionet du får, kjernen forstørret og hvor liten den er: som en ert midt på en fotballbane.',
    keywords: [
      'protontall',
      'nukleontall',
      'nøytrontall',
      'isotop',
      'ion',
      'elektronskall',
      'kjerne',
      'grunnstoff',
      'atomnummer',
      'periodesystemet',
      'periode',
      'gruppe',
      'nuklidesymbol',
      'målestokk',
      'tomrom',
    ],
    load: () => import('./AtometsOppbygning'),
  },
  {
    id: 'rutherford',
    chapter: '7',
    sections: ['7A'],
    title: 'Rutherfords forsøk: α-partikler mot en tynn gullfolie',
    summary:
      'Skyt α-partikler mot gullfolie og tell hvor de havner. Sammenlign med det Thomsons rosinbolle forutsier, og se hvorfor de få som kastes tilbake, viser at atomet har en liten, tung og positiv kjerne.',
    keywords: [
      'Rutherford',
      'Thomson',
      'rosinbollemodellen',
      'spredningsforsøk',
      'alfapartikkel',
      'α-partikkel',
      'gullfolie',
      'avbøyning',
      'atomkjerne',
      'atommodell',
      'americium',
      'røykvarsler',
      'KM1',
      'KM2',
      'KM13',
    ],
    load: () => import('./Rutherford'),
  },
  {
    id: 'bohr-hydrogen',
    chapter: '7',
    sections: ['7B', '7C'],
    title: 'Bohrs atommodell: energinivåer i hydrogen',
    summary:
      'Et spektralrør som lyser rosa og sollys gjennom solatmosfæren: velg en overgang mellom to energinivåer, se elektronet hoppe mellom banene i ett hydrogenatom og fotonet som sendes ut eller tas opp, med energi, frekvens og bølgelengde.',
    keywords: [
      'energinivå',
      'foton',
      'Balmer',
      'Lyman',
      'Paschen',
      'emisjon',
      'absorpsjon',
      'grunntilstand',
      'ionisering',
      'E = hf',
      'spektralrør',
      'elektronbane',
      'Bohr-radius',
      'solatmosfære',
      'mørke linjer',
    ],
    load: () => import('./BohrHydrogen'),
  },
  {
    id: 'spektre',
    chapter: '7',
    sections: ['7C'],
    title: 'Spektre: kontinuerlig, emisjon og absorpsjon',
    summary:
      'Sammenlign spektrene til hydrogen, helium, natrium og kvikksølv med sollys, og se at linjene er fingeravtrykk for grunnstoffene.',
    keywords: [
      'spektrallinjer',
      'linjespekter',
      'emisjonsspekter',
      'absorpsjonsspekter',
      'Fraunhofer',
      'sollys',
      'fingeravtrykk',
      'fotonenergi',
    ],
    load: () => import('./Spektre'),
  },
  {
    id: 'nordlys',
    chapter: '7',
    sections: ['7B', '7C'],
    title: 'Nordlys: grønt, rødt og blåfiolett lys fra lufta',
    summary:
      'Elektroner fra solvinden får oksygen og nitrogen til å sende ut fotoner med bestemte farger. Se hvilken høyde hver farge kommer fra, overgangen mellom energinivåene og fotonenergien.',
    keywords: [
      'nordlys',
      'oksygen',
      'nitrogen',
      'eksitasjon',
      'energinivå',
      'foton',
      'fotonenergi',
      'E = hf',
      'linjespekter',
      'solvind',
      'KM2',
      'KM13',
    ],
    load: () => import('./Nordlys'),
  },
];

export default viz;
