import type { VizMeta } from '../../types';

/** Kapittel 13 Formering (Bi 1). Delkapitlene er ikke bekreftet ennå, så `sections` er tom. */
const viz: VizMeta[] = [
  {
    id: 'kjonnet-og-ukjonnet',
    chapter: '13',
    sections: [],
    title: 'Kjønnet og ukjønnet formering',
    summary:
      'Følg to bestander av samme art, én med kloner og én med kjønnet formering, når miljøet blir varmere. Se hvorfor klonene vokser raskest i et stabilt miljø, og hvorfor variasjon redder bestanden når miljøet endrer seg.',
    keywords: [
      'kjønnet formering',
      'ukjønnet formering',
      'kloner',
      'genetisk variasjon',
      'meiose',
      'befruktning',
      'naturlig utvalg',
      'tilpasning',
      'den doble prisen for kjønnet formering',
      'bladlus',
      'miljøendring',
      'bæreevne',
      'KM6',
      'KM2',
    ],
    load: () => import('./KjonnetOgUkjonnet'),
  },
  {
    id: 'menstruasjonssyklusen',
    chapter: '13',
    sections: [],
    title: 'Menstruasjonssyklusen',
    summary:
      'Gå gjennom en syklus på 28 dager og se FSH, LH, østrogen og progesteron, follikkelen, eggløsningen, gulelegemet og livmorslimhinnen. Slå på graviditet eller p-piller og se hvordan tilbakekoblingen endrer alt.',
    keywords: [
      'menstruasjonssyklus',
      'menstruasjon',
      'eggløsning',
      'FSH',
      'LH',
      'østrogen',
      'progesteron',
      'hCG',
      'follikkel',
      'gulelegeme',
      'livmorslimhinne',
      'hypofysen',
      'negativ tilbakekobling',
      'positiv tilbakekobling',
      'graviditet',
      'p-piller',
      'prevensjon',
      'hormoner',
      'KM4',
      'KM3',
    ],
    load: () => import('./Menstruasjonssyklusen'),
  },
  {
    id: 'planters-formering',
    chapter: '13',
    sections: [],
    title: 'Planters formering',
    summary:
      'Trinn for trinn fra blomst til frø og frukt: pollinering, pollenslangen og den doble befruktningen. Sammenlign med ukjønnet formering med utløpere og knoller, som gir kloner.',
    keywords: [
      'blomst',
      'pollinering',
      'krysspollinering',
      'pollen',
      'støvbærer',
      'pistill',
      'arr',
      'griffel',
      'fruktknute',
      'frøemne',
      'eggcelle',
      'pollenslange',
      'dobbel befruktning',
      'frøhvite',
      'kim',
      'frø',
      'frukt',
      'vegetativ formering',
      'utløpere',
      'knoller',
      'kloner',
      'KM3',
    ],
    load: () => import('./PlantersFormering'),
  },
];

export default viz;
