/**
 * Fargene i de illustrerte scenene. Verdiene er CSS-variabler (scene.css) og følger lyst og mørkt tema.
 * Bruk alltid disse (eller VIZ for fysiske størrelser), aldri egne fargekoder.
 */
export const SCENE = {
  skyTop: 'var(--sc-sky-top)',
  skyBottom: 'var(--sc-sky-bottom)',
  sun: 'var(--sc-sun)',
  sunGlow: 'var(--sc-sun-glow)',
  cloud: 'var(--sc-cloud)',
  cloudShade: 'var(--sc-cloud-shade)',
  space: 'var(--sc-space)',
  spaceGlow: 'var(--sc-space-glow)',
  star: 'var(--sc-star)',
  mountain: 'var(--sc-mountain)',
  mountainShade: 'var(--sc-mountain-shade)',
  snowcap: 'var(--sc-snowcap)',
  hillFar: 'var(--sc-hill-far)',
  hillNear: 'var(--sc-hill-near)',
  grass: 'var(--sc-grass)',
  grassDark: 'var(--sc-grass-dark)',
  foliage: 'var(--sc-foliage)',
  foliageDark: 'var(--sc-foliage-dark)',
  trunk: 'var(--sc-trunk)',
  soil: 'var(--sc-soil)',
  soilDark: 'var(--sc-soil-dark)',
  asphalt: 'var(--sc-asphalt)',
  asphaltDark: 'var(--sc-asphalt-dark)',
  asphaltWet: 'var(--sc-asphalt-wet)',
  roadLine: 'var(--sc-road-line)',
  gravel: 'var(--sc-gravel)',
  gravelDark: 'var(--sc-gravel-dark)',
  concrete: 'var(--sc-concrete)',
  concreteDark: 'var(--sc-concrete-dark)',
  snow: 'var(--sc-snow)',
  snowShade: 'var(--sc-snow-shade)',
  ice: 'var(--sc-ice)',
  iceShine: 'var(--sc-ice-shine)',
  water: 'var(--sc-water)',
  waterLight: 'var(--sc-water-light)',
  waterDeep: 'var(--sc-water-deep)',
  woodLight: 'var(--sc-wood-light)',
  wood: 'var(--sc-wood)',
  woodDark: 'var(--sc-wood-dark)',
  metalLight: 'var(--sc-metal-light)',
  metal: 'var(--sc-metal)',
  metalDark: 'var(--sc-metal-dark)',
  rubber: 'var(--sc-rubber)',
  rubberLight: 'var(--sc-rubber-light)',
  plastic: 'var(--sc-plastic)',
  plasticShade: 'var(--sc-plastic-shade)',
  glass: 'var(--sc-glass)',
  glassEdge: 'var(--sc-glass-edge)',
  stone: 'var(--sc-stone)',
  stoneDark: 'var(--sc-stone-dark)',
  brick: 'var(--sc-brick)',
  copper: 'var(--sc-copper)',
  gold: 'var(--sc-gold)',
  skin: 'var(--sc-skin)',
  skinShade: 'var(--sc-skin-shade)',
  hair: 'var(--sc-hair)',
  denim: 'var(--sc-denim)',
  wall: 'var(--sc-wall)',
  wallShade: 'var(--sc-wall-shade)',
  floor: 'var(--sc-floor)',
  floorDark: 'var(--sc-floor-dark)',
  bench: 'var(--sc-bench)',
  benchEdge: 'var(--sc-bench-edge)',
  shadow: 'var(--sc-shadow)',
  highlight: 'var(--sc-highlight)',
  outline: 'var(--sc-outline)',
  glow: 'var(--sc-glow)',
  hot: 'var(--sc-hot)',
  warm: 'var(--sc-warm)',
  cold: 'var(--sc-cold)',
  display: 'var(--sc-display)',
  displayText: 'var(--sc-display-text)',
} as const;

/** Lakk og tøy: bilen, jakka, kassen. Navnene er norske, så de kan stå i props: `<Bil lakk="rod" />`. */
export const PAINTS = {
  rod: 'var(--sc-paint-red)',
  blaa: 'var(--sc-paint-blue)',
  gronn: 'var(--sc-paint-green)',
  gul: 'var(--sc-paint-yellow)',
  oransje: 'var(--sc-paint-orange)',
  lilla: 'var(--sc-paint-purple)',
  hvit: 'var(--sc-paint-white)',
  graa: 'var(--sc-paint-grey)',
  svart: 'var(--sc-paint-black)',
} as const;

export type PaintName = keyof typeof PAINTS;

/** En navngitt farge fra PAINTS eller en hvilken som helst CSS-farge (f.eks. VIZ.applied eller SCENE.wood). */
export function paint(p: PaintName | string): string {
  return p in PAINTS ? PAINTS[p as PaintName] : p;
}
