import type { VizMeta } from '../../types';

/** Kapittel 10 Transportsystemer i dyr (Bi 1). Delkapitlene er ikke bekreftet ennå, så `sections` er tom. */
const viz: VizMeta[] = [
  {
    id: 'kretslop-hos-dyr',
    chapter: '10',
    sections: [],
    title: 'Blodkretsløp hos ulike dyr',
    summary:
      'Sammenlign det åpne kretsløpet hos insekter med enkelt kretsløp hos fisk og dobbelt kretsløp hos amfibier, krypdyr, fugler og pattedyr. Se oksygenrikt og oksygenfattig blod strømme, hvor det blandes, og hvordan blodtrykket endrer seg.',
    keywords: [
      'blodkretsløp',
      'åpent kretsløp',
      'lukket kretsløp',
      'enkelt kretsløp',
      'dobbelt kretsløp',
      'hjerte',
      'forkammer',
      'hjertekammer',
      'hjerterom',
      'hemolymfe',
      'lungekretsløpet',
      'kroppskretsløpet',
      'blodtrykk',
      'oksygenrikt blod',
      'oksygenfattig blod',
      'endoterm',
      'ektoterm',
      'insekt',
      'fisk',
      'amfibie',
      'krypdyr',
      'fugl',
      'pattedyr',
      'KM2',
      'KM3',
    ],
    load: () => import('./KretslopHosDyr'),
  },
  {
    id: 'respirasjon-hos-dyr',
    chapter: '10',
    sections: [],
    title: 'Gassutveksling og kroppsstørrelse',
    summary:
      'Gjør et dyr større og se hvorfor diffusjon gjennom huden bare holder for dyr på noen få millimeter, og hvordan trakeer, gjeller, lunger og fuglelunger med luftsekker løser problemet.',
    keywords: [
      'respirasjon',
      'gassutveksling',
      'diffusjon',
      'diffusjonsavstand',
      'Ficks lov',
      'overflate',
      'hudånding',
      'trakeer',
      'åndehull',
      'gjeller',
      'lunger',
      'alveoler',
      'lungeblærer',
      'luftsekker',
      'fuglelunger',
      'parabronkier',
      'kroppsstørrelse',
      'KM2',
      'KM3',
    ],
    load: () => import('./RespirasjonHosDyr'),
  },
  {
    id: 'gjeller-motstrom',
    chapter: '10',
    sections: [],
    title: 'Motstrøm i gjellene',
    summary:
      'Følg O₂ i vannet og blodet langs en gjellelamell, og sammenlign motstrøm med medstrøm: hvorfor tar fisken opp mye mer O₂ når blodet og vannet strømmer hver sin vei?',
    keywords: [
      'gjeller',
      'gjellelamell',
      'gjellefilament',
      'motstrøm',
      'motstrømsprinsippet',
      'medstrøm',
      'fisk',
      'oksygenmetning',
      'diffusjon',
      'konsentrasjonsforskjell',
      'gassutveksling',
      'KM3',
    ],
    load: () => import('./GjellerMotstrom'),
  },
];

export default viz;
