import type { VizMeta } from '../../types';

/** Kapittel 4 Kollisjoner og eksplosjoner. */
const viz: VizMeta[] = [
  {
    id: 'impuls',
    chapter: '4',
    sections: ['4B'],
    title: 'Impulsloven: kort eller lang støttid',
    summary:
      'Et egg faller på en tynn matte, et håndkle eller en pute, og en bilfører stopper mot rattet, i beltet eller i kollisjonsputa. Arealet under F-t-grafen er det samme, men kort støttid gir stor kraft. Spill av støtet i sakte film.',
    keywords: [
      'impuls',
      'impulsloven',
      'bevegelsesmengde',
      'støttid',
      'F-t-graf',
      'gjennomsnittskraft',
      'bremselengde',
      'egg',
      'pute',
      'kollisjonspute',
      'bilbelte',
      'knusesone',
      'hjelm',
    ],
    load: () => import('./Impuls'),
  },
  {
    id: 'krasjtest',
    chapter: '4',
    sections: ['4A', '4B'],
    title: 'Krasjtest: knusesone, belte og kollisjonspute',
    summary:
      'Kjør en bil inn i en betongvegg og se hvordan knusesonen, beltet og puta forlenger bremsestrekningen og stoppetiden. Impulsloven gir kraften på passasjeren og «g-kreftene».',
    keywords: [
      'krasjtest',
      'kollisjon',
      'knusesone',
      'bilbelte',
      'kollisjonspute',
      'impuls',
      'impulsloven',
      'bevegelsesmengde',
      'stoppetid',
      'gjennomsnittskraft',
      'g-krefter',
      'stiv bil',
      'trafikksikkerhet',
      'KM5',
      'KM7',
    ],
    load: () => import('./Krasjtest'),
  },
  {
    id: 'curling',
    chapter: '4',
    sections: ['4A', '4C', '4D'],
    title: 'Curling: rett treff på en stein som ligger i ro',
    summary:
      'En curlingstein treffer en like tung stein midt i huset. Velg hvor elastisk støtet er, og se hvorfor den første steinen stopper helt i et elastisk støt, mens bevegelsesmengden alltid er bevart.',
    keywords: [
      'curling',
      'curlingstein',
      'bevegelsesmengde',
      'bevaring av bevegelsesmengde',
      'sentralt støt',
      'elastisk støt',
      'uelastisk støt',
      'fullstendig uelastisk støt',
      'kinetisk energi',
      'energitap',
      'like masser',
      'bytter fart',
      'stroboskopbilde',
      'indre krefter',
      'Newtons 3. lov',
      'KM7',
      'KM8',
    ],
    load: () => import('./Curling'),
  },
  {
    id: 'sentrale-stot',
    chapter: '4',
    sections: ['4C', '4D'],
    title: 'Sentrale støt mellom to labvogner',
    summary:
      'To labvogner med fjær, gummidemper eller borrelås støter sammen på en bane med målebånd. Velg masser og farter, og se støtet i sakte film: Σp er bevart hele tiden, også midt i støtet, men kinetisk energi bare i elastiske støt.',
    keywords: [
      'bevegelsesmengde',
      'bevaring av bevegelsesmengde',
      'sentralt støt',
      'elastisk støt',
      'uelastisk støt',
      'fullstendig uelastisk støt',
      'kinetisk energi',
      'energitap',
      'kollisjon',
      'labvogn',
      'dynamikkvogn',
      'fjær',
      'borrelås',
      'kraftpar',
      'Newtons 3. lov',
      'indre krefter',
      'impuls',
      'KM7',
      'KM8',
    ],
    load: () => import('./SentraleStot'),
  },
  {
    id: 'eksplosjon',
    chapter: '4',
    sections: ['4B', '4C'],
    title: 'Eksplosjon og rekyl',
    summary:
      'To skøyteløpere dytter hverandre fra hverandre på isen, en fjær skyver to labvogner fra hverandre, eller et gevær skyter ut en kule. Σp er null før, under og etter, og den letteste får størst fart og mest energi.',
    keywords: [
      'bevegelsesmengde',
      'bevaring av bevegelsesmengde',
      'eksplosjon',
      'rekyl',
      'skøyter',
      'skøyteløper',
      'is',
      'dytt',
      'impuls',
      'impulsloven',
      'Newtons 3. lov',
      'kraftpar',
      'indre krefter',
      'labvogn',
      'fjær',
      'gevær',
      'jaktrifle',
      'kule',
      'kinetisk energi',
      'KM7',
    ],
    load: () => import('./Eksplosjon'),
  },
];

export default viz;
