import type { VizMeta } from '../../types';

/** Kapittel 7 Celledeling (Bi 1). Delkapitlene er ikke bekreftet ennå, så `sections` er tom. */
const viz: VizMeta[] = [
  {
    id: 'mitose',
    chapter: '7',
    sections: [],
    title: 'Cellesyklusen og mitosen',
    summary:
      'Gå gjennom interfasen og mitosen steg for steg i en dyrecelle eller plantecelle, og se kromosomene kopieres og fordeles mens DNA-mengden går fra 2c til 4c og tilbake.',
    keywords: [
      'mitose',
      'cellesyklus',
      'interfase',
      'G1',
      'S-fasen',
      'G2',
      'replikasjon',
      'profase',
      'metafase',
      'anafase',
      'telofase',
      'cytokinese',
      'kromosom',
      'søsterkromatider',
      'sentromer',
      'spoletråder',
      'sentriol',
      'celleplate',
      'diploid',
      'KM6',
    ],
    load: () => import('./Mitose'),
  },
  {
    id: 'meiose',
    chapter: '7',
    sections: [],
    title: 'Meiose og kjønnsceller',
    summary:
      'Følg meiose I og II med homologe kromosomer fra mor og far, slå overkrysning av og på, og se hvordan uavhengig fordeling gir 2ⁿ ulike kjønnsceller. Sammenlign med mitosen.',
    keywords: [
      'meiose',
      'meiose I',
      'meiose II',
      'kjønnsceller',
      'gameter',
      'homologe kromosomer',
      'overkrysning',
      'uavhengig fordeling',
      'haploid',
      'diploid',
      'genetisk variasjon',
      'kromosomtall',
      'befruktning',
      'mitose',
      'KM6',
    ],
    load: () => import('./Meiose'),
  },
  {
    id: 'regulering-av-celledeling',
    chapter: '7',
    sections: [],
    title: 'Regulering av celledelingen og kreft',
    summary:
      'Se kontrollpunktene i cellesyklusen, hvordan et sår gror og stopper ved kontakthemming, og hva som skjer når gasspedalen (proto-onkogener) eller bremsene (tumorsuppressorgener) slutter å virke.',
    keywords: [
      'regulering av celledeling',
      'cellesyklus',
      'kontrollpunkt',
      'G0',
      'kontakthemming',
      'sårheling',
      'vekst og reparasjon',
      'proto-onkogen',
      'onkogen',
      'tumorsuppressorgen',
      'p53',
      'mutasjon',
      'DNA-skade',
      'apoptose',
      'svulst',
      'kreft',
      'KM6',
    ],
    load: () => import('./ReguleringAvCelledeling'),
  },
];

export default viz;
