import type { VizMeta } from '../../types';

/** Kapittel 6 Bølger og stråling. */
const viz: VizMeta[] = [
  {
    id: 'bolger',
    chapter: '6',
    sections: ['6A'],
    title: 'Bølger: bølgelengde, frekvens og fart',
    summary:
      'Rist i et langt tau eller dytt i en spiralfjær på labbenken, og se at bølgen går bortover mens hvert punkt bare svinger. Mål bølgelengden på målebåndet og sammenlign med grafen for ett punkt.',
    keywords: ['v = λf', 'periode', 'amplitude', 'transversal', 'longitudinal', 'fortetning', 'fortynning', 'lyd', 'tau', 'spiralfjær', 'målebånd', 'bølgefart'],
    load: () => import('./Bolger'),
  },
  {
    id: 'ekko',
    chapter: '6',
    sections: ['6A'],
    title: 'Lyd og ekko: avstanden til lynet og dybden under båten',
    summary:
      'Mål tiden fra lynet til tordenen og finn avstanden med s = v · t, og se ekkoloddet på en fiskebåt måle dybden når lydpulsen går ned og opp igjen. Sammenlign bølgelengden λ = v / f i luft og vann.',
    keywords: ['lydfart', '340 m/s', '1500 m/s', 'ekko', 'ekkolodd', 'torden', 'lyn', 'ultralyd', 'refleksjon', 's = vt', 'λ = v/f', 'KM1', 'KM2'],
    load: () => import('./Ekko'),
  },
  {
    id: 'em-spekteret',
    chapter: '6',
    sections: ['6A', '6B'],
    title: 'Det elektromagnetiske spekteret i hverdagen',
    summary:
      'Dra langs spekteret fra DAB-radioen i bilen via mobilen, mikrobølgeovnen, fjernkontrollen og regnbuen til solkrem, røntgen og gammastråling. Se bølgelengden, frekvensen (c = λf) og fotonenergien (E = hf), og hvorfor bare noen typer stråling kan skade cellene.',
    keywords: [
      'elektromagnetisk stråling',
      'c = λf',
      'E = hf',
      'foton',
      'fotonenergi',
      'elektronvolt',
      'radiobølger',
      'mikrobølger',
      'infrarødt',
      'synlig lys',
      'ultrafiolett',
      'UV',
      'røntgen',
      'gammastråling',
      'ioniserende stråling',
      'mobil',
      'wifi',
      'mikrobølgeovn',
      'varmekamera',
      'fjernkontroll',
      'regnbue',
      'solkrem',
      'lysfarten',
      'KM2',
      'KM11',
    ],
    load: () => import('./EmSpekteret'),
  },
  {
    id: 'svart-legeme',
    chapter: '6',
    sections: ['6B'],
    title: 'Stråling fra svarte legemer',
    summary:
      'Fra en kokeplate som så vidt gløder, via smijern og glødetråd, til Sola og blåhvite stjerner: endre temperaturen og se fargen og Planck-kurven endre seg. Toppen følger Wiens lov, arealet under kurven følger Stefan–Boltzmanns lov, og stolpen viser hvor mye som er UV, synlig lys og IR.',
    keywords: [
      'Planck',
      'Wiens forskyvningslov',
      'Stefan–Boltzmann',
      'σT⁴',
      'λmaks',
      'temperatur',
      'farge',
      'glød',
      'kokeplate',
      'smijern',
      'glødelampe',
      'glødetråd',
      'stjerner',
      'Sola',
      'Betelgeuse',
      'Sirius',
      'Rigel',
      'Orion',
      'infrarødt',
      'ultrafiolett',
      'synlig lys',
      'kelvin',
    ],
    load: () => import('./SvartLegeme'),
  },
  {
    id: 'stralingsbalanse',
    chapter: '6',
    sections: ['6C'],
    title: 'Strålingsbalansen til jorda',
    summary:
      'Et snitt gjennom atmosfæren over norskekysten: snø, is og skyer reflekterer sollys, og drivhusgassene tar opp varmestrålingen fra bakken og sender halvparten tilbake ned. Endre albedoen og drivhusgassene, og se temperaturen ved bakken finne en ny likevekt.',
    keywords: [
      'drivhuseffekt',
      'drivhusgasser',
      'CO₂',
      'vanndamp',
      'albedo',
      'snø',
      'havis',
      'skyer',
      'solarkonstant',
      'S/4',
      'σT⁴',
      'varmestråling',
      'infrarødt',
      'likevekt',
      '255 K',
      '288 K',
      'klima',
      'énlagsmodell',
    ],
    load: () => import('./Stralingsbalanse'),
  },
  {
    id: 'solcellepanel',
    chapter: '6',
    sections: ['6C'],
    title: 'Solcellepanel ved hytta: sommer, vinter og beste vinkel',
    summary:
      'Vipp et solcellepanel og se hvordan effekten P = η · I · A · cos θ avhenger av solhøyden og vinkelen mellom sollyset og normalen. Sammenlign sommer og vinter fra Kristiansand til Tromsø, og finn den beste vinkelen.',
    keywords: [
      'solcelle',
      'solenergi',
      'virkningsgrad',
      'innstråling',
      'W/m²',
      'cos θ',
      'normal',
      'solhøyde',
      'innfallsvinkel',
      'luftmasse',
      'mørketid',
      'midnattssol',
      'breddegrad',
      'årstider',
      'fornybar energi',
      'KM2',
      'KM3',
      'KM8',
      'KM12',
    ],
    load: () => import('./Solcellepanel'),
  },
];

export default viz;
